networks:
  lua-net:

services:
  redis:
    image: redis:latest
    container_name: redis-lua
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6374:6379"
    networks:
      - lua-net
